name: Automated testing on push by Github Actions
run-name: ${{ github.actor}} is testing matrix multiplication...
on: 
  push:
    branches:
      - main
jobs:
  build-test-container-on-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The job is running on a ${{ runner.os }} server hosted by GitHub."
      - uses: actions/checkout@v2
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
      - name: Create folder
        run: mkdir -p build
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build
      - name: CMake build
        run: cmake --build ${{ github.workspace }}/build
      - name: Run unit tests
        working-directory: ${{ github.workspace }}/build
        run: ./build/test_multiplication