name: Build Container, Deploy and Automate Testing
run-name: ${{ github.actor }} is testing matrix multiplication inside a Docker container...

on: 
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The job is running on a ${{ runner.os }} server hosted by GitHub."

      - uses: actions/checkout@v4
        with:
            submodules: recursive


      - name: Log in to the Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true



  run-docker-container-test:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
      
    steps:

      - name: Run Docker Image
        run: |
          export IMAGE_NAME_FULL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker run --rm  ${IMAGE_NAME_FULL,,}:main > test.log 2>&1

      - name: Export Test Log
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test.log
